name = "IncidenceGraphs"
uuid = "2dd57018-faeb-4749-b5d6-4036f5ed0de8"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez+git@bsc.es>"]
version = "0.1.0"

[deps]
DynamicSparseArrays = "8086fd22-9a0c-46a5-a6c8-6e24676501fe"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DynamicSparseArrays = "0.7"
